"""Remove tema_preferido e adiciona data_edicao

Revision ID: 9811dce39b57
Revises: 6a1061c2d651
Create Date: 2025-09-25 15:17:27.360919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9811dce39b57'
down_revision = '6a1061c2d651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_edicao', sa.DateTime(), nullable=True))
    op.drop_column('users', 'tema_preferido')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tema_preferido', mysql.VARCHAR(length=20), server_default=sa.text("'futurist'"), nullable=True))
    op.drop_column('users', 'data_edicao')
    # ### end Alembic commands ###
